apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    name: app

---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: app
spec:
  selector:
    app: ui
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: app
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: public.ecr.aws/aws-containers/retail-store-sample-ui:1.2.4
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '8080'
            - name: RETAIL_UI_THEME
              value: 'teal'
            - name: RETAIL_UI_DISABLE_DEMO_WARNINGS
              value: 'false'
            - name: RETAIL_UI_ENDPOINTS_CATALOG
              value: 'http://catalog.app'
            - name: RETAIL_UI_ENDPOINTS_CARTS
              value: 'http://cart.app'
            - name: RETAIL_UI_ENDPOINTS_ORDERS
              value: 'http://orders.app'
            - name: RETAIL_UI_ENDPOINTS_CHECKOUT
              value: 'http://checkout.app'
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
